name: Build Mac Intel (Legacy)

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-mac-intel:
    runs-on: macos-13 # This triggers an Intel (x86_64) runner
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install PySide6 pymupdf pyinstaller cryptography pillow

      - name: Decrypt Template
        env:
          PDF_KEY: ${{ secrets.PDF_KEY }}
        run: |
           python -c "from cryptography.fernet import Fernet; import os; key = os.environ['PDF_KEY']; f = Fernet(key.encode()); data = open('DocSolScantron.enc', 'rb').read(); open('DocSolScantron.pdf', 'wb').write(f.decrypt(data))"

      - name: Build App
        # Building on Intel automatically creates an x86_64 executable
        run: |
          pyinstaller --noconsole --onefile --name "AutoBubbler" --icon "AutoBubbler.png" --add-data "DocSolScantron.pdf:." --add-data "AutoBubbler.ico:." AutoBubbler.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoBubbler-Mac-Intel
          path: dist

      - name: Zip Application
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          cd dist
          ditto -c -k --keepParent AutoBubbler.app AutoBubbler-Mac-Intel.zip

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/AutoBubbler-Mac-Intel.zip